### ISSUE TITLE
Demonstrate Issue Tracker To Armen

### ISSUE THREAD

**Issue by Jabittner** [Jabittner/openSAFT#1]
No point to have a TODO list in README.

**Comment by ArmenAmirkhanian** [comment]
I see. At least my push works!

**Comment by Jabittner** [comment]
this issue tracker actually works pretty simplistic, I'm surprised.

**Comment by ArmenAmirkhanian** [comment]
Yup, I like it. How would you resolve the issue through a push? Can you? Or would you have to push, then go to the issue and close it?

**Comment by Jabittner** [comment]
idk..
ᐧ

**Comment by ArmenAmirkhanian** [comment]
WHAT DO YOU KNOW!!!!!???
